%% FileIO String Generator
% How to use: change taskID and foldername. Note they should correspond to each other.

taskID = [1,2,3,4,5,6];
foldername = [{'folder1'} {'folder2'} {'folder2'} {'folder2'} ...
              {'folder2'} {'folder2'}];
          
          
if length(taskID)~=length(foldername)
    error('Different taskID and folder name');
end

FileIOStr = cell(length(taskID) + 1, 1);
for ii = 1:length(taskID)
    if ii == 1
        FileIOStr{ii} = ...
    [sprintf('if(taskID == %d) \n',taskID(ii)),...
    sprintf('sourcepath = fullfile(prefix, ''%s'', ''output''); \n', foldername{ii}), ...
    sprintf('outputpath = fullfile(sourcepath, ''NewMask''); \n'), ...
    sprintf('filename_skel0 = fullfile(prefix, ''%s'', ''ManualLabel'');\n',foldername{ii}), ...
    sprintf('firstframeName = sprintf(''%%04d'', firstframe);\n'), ...
    sprintf('firstframeName = [firstframeName, ''.tif''];\n'), ...
    sprintf('filename_skel0 = fullfile(filename_skel0, firstframeName);\n')];
        
    else
        FileIOStr{ii} = ...
    [sprintf('elseif(taskID == %d) \n',taskID(ii)),...
    sprintf('sourcepath = fullfile(prefix, ''%s'', ''output''); \n', foldername{ii}), ...
    sprintf('outputpath = fullfile(sourcepath, ''NewMask''); \n'), ...
    sprintf('filename_skel0 = fullfile(prefix, ''%s'', ''ManualLabel'');\n',foldername{ii}), ...
    sprintf('firstframeName = sprintf(''%%04d'', firstframe);\n'), ...
    sprintf('firstframeName = [firstframeName, ''.tif''];\n'), ...
    sprintf('filename_skel0 = fullfile(filename_skel0, firstframeName);\n')];
    end
    FileIOStr{end} = sprintf('end \n');
end
finalstr = '';
for jj = 1:length(FileIOStr)
    finalstr = [finalstr FileIOStr{jj}];
end

    